{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataTask"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Received underlying optinal error."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/appcraft_auth_ios\/acautherror\/responseerror\/datatask(error:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/appcraft-auth-ios\/documentation\/appcraft_auth_ios\/ACAuthError\/ResponseError\/dataTask(error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Task error returned by URL loading APIs."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataTask"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"title":"ACAuthError.ResponseError.dataTask(error:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:17appcraft_auth_ios11ACAuthErrorO08ResponseE0O8dataTaskyAEs0E0_pSg_tcAEmF","modules":[{"name":"appcraft-auth-ios"}]},"hierarchy":{"paths":[["doc:\/\/appcraft-auth-ios\/documentation\/appcraft_auth_ios","doc:\/\/appcraft-auth-ios\/documentation\/appcraft_auth_ios\/ACAuthError","doc:\/\/appcraft-auth-ios\/documentation\/appcraft_auth_ios\/ACAuthError\/ResponseError"]]},"references":{"doc://appcraft-auth-ios/documentation/appcraft_auth_ios":{"role":"collection","title":"appcraft-auth-ios","abstract":[],"identifier":"doc:\/\/appcraft-auth-ios\/documentation\/appcraft_auth_ios","kind":"symbol","type":"topic","url":"\/documentation\/appcraft_auth_ios"},"doc://appcraft-auth-ios/documentation/appcraft_auth_ios/ACAuthError/ResponseError/dataTask(error:)":{"role":"symbol","title":"ACAuthError.ResponseError.dataTask(error:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataTask"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Task error returned by URL loading APIs."}],"identifier":"doc:\/\/appcraft-auth-ios\/documentation\/appcraft_auth_ios\/ACAuthError\/ResponseError\/dataTask(error:)","kind":"symbol","type":"topic","url":"\/documentation\/appcraft_auth_ios\/acautherror\/responseerror\/datatask(error:)"},"doc://appcraft-auth-ios/documentation/appcraft_auth_ios/ACAuthError/ResponseError":{"role":"symbol","title":"ACAuthError.ResponseError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseError"}],"abstract":[{"type":"text","text":"Represents the error reason during networking response phase."}],"identifier":"doc:\/\/appcraft-auth-ios\/documentation\/appcraft_auth_ios\/ACAuthError\/ResponseError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseError"}],"url":"\/documentation\/appcraft_auth_ios\/acautherror\/responseerror"},"doc://appcraft-auth-ios/documentation/appcraft_auth_ios/ACAuthError":{"role":"symbol","title":"ACAuthError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ACAuthError"}],"abstract":[],"identifier":"doc:\/\/appcraft-auth-ios\/documentation\/appcraft_auth_ios\/ACAuthError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ACAuthError"}],"url":"\/documentation\/appcraft_auth_ios\/acautherror"}}}